using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OFMProfileAnalyze
{
    public enum enumMake
    {
        emake_Acura = 1,
        emake_Alfa_____Romeo = 0x38,
        emake_AM_____General = 2,
        emake_Audi = 3,
        emake_Bentley = 0x37,
        emake_BMW = 4,
        emake_Buick = 5,
        emake_BYD = 0x30,
        emake_Cadillac = 6,
        emake_Chery = 0x31,
        emake_Chevrolet = 7,
        emake_Chrysler = 8,
        emake_Citro_n = 0x39,
        emake_Daewoo = 9,
        emake_Daihatsu = 50,
        emake_Dodge = 10,
        emake_Eagle = 11,
        emake_Faw = 0x3b,
        emake_Fiat = 0x29,
        emake_Fiat_FCA_ = 0x3e,
        emake_Ford = 12,
        emake_Geo = 13,
        emake_GM = 60,
        emake_GMC = 14,
        emake_Honda = 15,
        emake_Hummer = 0x10,
        emake_Hyundai = 0x11,
        emake_Infiniti = 0x12,
        emake_Isuzu = 0x2a,
        emake_Jaguar = 0x13,
        emake_Jeep = 20,
        emake_Kia = 0x15,
        emake_Land_____Rover = 0x16,
        emake_Lexus = 0x17,
        emake_Lifan = 0x3a,
        emake_Lincoln = 0x18,
        emake_MAX = 0xffff,
        emake_Mazda = 0x19,
        emake_Mercedes_Benz = 0x1a,
        emake_Mercury = 0x1b,
        emake_MG = 0x34,
        emake_Mini = 0x1c,
        emake_Mitsubishi = 0x2b,
        emake_Nissan = 0x1d,
        emake_Oldsmobile = 30,
        emake_Opel = 0x3d,
        emake_Others = 0xfffe,
        emake_Peugeot = 0x35,
        emake_Plymouth = 0x1f,
        emake_Pontiac = 0x20,
        emake_Porsche = 0x2c,
        emake_Ram = 0x21,
        emake_Renault = 0x3f,
        emake_Rover = 0x40,
        emake_Saab = 0x22,
        emake_Saturn = 0x23,
        emake_Scion = 0x24,
        emake_Seat = 0x36,
        emake_Smart = 0x2d,
        emake_Sprinter = 0x41,
        emake_SRT = 0x25,
        emake_Ssangyong = 0x33,
        emake_Subaru = 0x2e,
        emake_Suzuki = 0x2f,
        emake_Toyota = 0x26,
        emake_UNKNOWN = 0,
        emake_Volkswagen = 0x27,
        emake_Volvo = 40
    }
}
