using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OFMProfileAnalyze
{
    //Create EnumType
    public enum enumtype
    {
        BufferNames,
        Checksums,
        Connector,
        DLCs,
        DLCVoltages,
        DtcDisplayType,
        DtcStatuses,
        endian,
        Fields,
        InitTypes,
        InnovaGroups,
        Makes,
        Manufacturers,
        monitortype,
        PD_Resitors,
        Protocols,
        Resistors,
        sign,
        UartData,
        VIN10ToYears,
        Vrefs,
        Years,
        command,
        commandlist,
        convertunit,
        dtcreadtype,
        ecuinfotype,
        engine,
        erasetype,
        formula,
        formula_info,
        isocode,
        itemid,
        itemname,
        lookuptable,
        messageid,
        models,
        monitorid,
        profileid,
        readdtccommandlist,
        sf_formularoem,
        sf_FunctionID,
        sf_itemFunction,
        sf_keycon,
        sf_valuetable,
        sf_valuetablestring,
        sfconditionid,
        sfsreenid,
        sfsreenitem_bodyitem,
        sfsreenitem_bodykey,
        sfsreenitem_desp1,
        sfsreenitem_desp2,
        sfsreenitem_footer,
        sfsreenitem_header,
        sfvariableid,
        sfvarstring,
        sfvarunit,
        subsystem,
        system,
        table_next,
        tableid,
        timing,
        unit,
        unitconvertid,
        variant,
        version,
        trim,
        signalid,
        typesignalid,
        ecuid,
        ofm_ItemName,
        bodycode,
        unknowenum
    }
}
