using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OFMProfileAnalyze
{
    public enum enumProtocol
    {
        eprotocol_PROTOCOL_92HM = 0x1c,
        eprotocol_PROTOCOL_95HM = 0x1b,
        eprotocol_PROTOCOL_ALDL = 0x3f,
        eprotocol_PROTOCOL_BMW_CAN = 0x35,
        eprotocol_PROTOCOL_BOSCH = 9,
        eprotocol_PROTOCOL_CAN = 0x1d,
        eprotocol_PROTOCOL_CAN_C = 0x41,
        eprotocol_PROTOCOL_CAN_C_UDS = 0x12,
        eprotocol_PROTOCOL_CAN_D2 = 0x3d,
        eprotocol_PROTOCOL_CAN_GGD = 0x3e,
        eprotocol_PROTOCOL_CAN_I_UDS = 0x13,
        eprotocol_PROTOCOL_CAN_UDS = 60,
        eprotocol_PROTOCOL_CAN250KBAUD = 7,
        eprotocol_PROTOCOL_CAN500KBAUD = 5,
        eprotocol_PROTOCOL_CANUDS = 60,
        eprotocol_PROTOCOL_CCD = 0x20,
        eprotocol_PROTOCOL_CCD2 = 0x15,
        eprotocol_PROTOCOL_D2 = 0x49,
        eprotocol_PROTOCOL_DDL1 = 0x30,
        eprotocol_PROTOCOL_DDL2 = 0x3a,
        eprotocol_PROTOCOL_DS1 = 70,
        eprotocol_PROTOCOL_DS2 = 0x3b,
        eprotocol_PROTOCOL_DS2_MID = 0x47,
        eprotocol_PROTOCOL_GGD = 0x4a,
        eprotocol_PROTOCOL_GMLAN = 0x40,
        eprotocol_PROTOCOL_H99B = 0x1a,
        eprotocol_PROTOCOL_ISO9141 = 3,
        eprotocol_PROTOCOL_J1708 = 0x51,
        eprotocol_PROTOCOL_J1939 = 0x52,
        eprotocol_PROTOCOL_KW = 15,
        eprotocol_PROTOCOL_KW1281 = 0x10,
        eprotocol_PROTOCOL_KW2000 = 4,
        eprotocol_PROTOCOL_KWFB = 0x34,
        eprotocol_PROTOCOL_KWSSM = 0x39,
        eprotocol_PROTOCOL_MAX = 0xffff,
        eprotocol_PROTOCOL_MB_ISO = 0x33,
        eprotocol_PROTOCOL_MCAN = 0x18,
        eprotocol_PROTOCOL_MCAN_____UDS = 0x19,
        eprotocol_PROTOCOL_MUT = 0x11,
        eprotocol_PROTOCOL_NO = 0,
        eprotocol_PROTOCOL_OBD1 = 0x2a,
        eprotocol_PROTOCOL_PWM = 2,
        eprotocol_PROTOCOL_RESERVE_10 = 10,
        eprotocol_PROTOCOL_RESERVE_11 = 11,
        eprotocol_PROTOCOL_RESERVE_12 = 12,
        eprotocol_PROTOCOL_RESERVE_13 = 13,
        eprotocol_PROTOCOL_RESERVE_14 = 14,
        eprotocol_PROTOCOL_RESERVE_20 = 20,
        eprotocol_PROTOCOL_RESERVE_30 = 30,
        eprotocol_PROTOCOL_RESERVE_31 = 0x1f,
        eprotocol_PROTOCOL_RESERVE_34 = 0x22,
        eprotocol_PROTOCOL_RESERVE_35 = 0x23,
        eprotocol_PROTOCOL_RESERVE_36 = 0x24,
        eprotocol_PROTOCOL_RESERVE_37 = 0x25,
        eprotocol_PROTOCOL_RESERVE_38 = 0x26,
        eprotocol_PROTOCOL_RESERVE_39 = 0x27,
        eprotocol_PROTOCOL_RESERVE_40 = 40,
        eprotocol_PROTOCOL_RESERVE_41 = 0x29,
        eprotocol_PROTOCOL_RESERVE_43 = 0x2b,
        eprotocol_PROTOCOL_RESERVE_44 = 0x2c,
        eprotocol_PROTOCOL_RESERVE_45 = 0x2d,
        eprotocol_PROTOCOL_RESERVE_46 = 0x2e,
        eprotocol_PROTOCOL_RESERVE_47 = 0x2f,
        eprotocol_PROTOCOL_RESERVE_50 = 50,
        eprotocol_PROTOCOL_RESERVE_76 = 0x4c,
        eprotocol_PROTOCOL_RESERVE_77 = 0x4d,
        eprotocol_PROTOCOL_RESERVE_78 = 0x4e,
        eprotocol_PROTOCOL_RESERVE_79 = 0x4f,
        eprotocol_PROTOCOL_RESERVE_80 = 80,
        eprotocol_PROTOCOL_SCI = 0x21,
        eprotocol_PROTOCOL_SDL = 0x16,
        eprotocol_PROTOCOL_SWCAN = 0x31,
        eprotocol_PROTOCOL_TCAN = 0x42,
        eprotocol_PROTOCOL_TPCAN_1_6_KW1281 = 0x37,
        eprotocol_PROTOCOL_TPCAN_1_6_KW2000 = 0x38,
        eprotocol_PROTOCOL_TPCAN_2_0 = 0x36,
        eprotocol_PROTOCOL_UBP = 0x17,
        eprotocol_PROTOCOL_VPW = 1,
        eprotocol_PROTOCOL_XCAN250KBAUD = 8,
        eprotocol_PROTOCOL_XCAN500KBAUD = 6,
        eprotocol_Suzuki_SDL = 0x4b,
        eprotocol_UNKNOWN = 0
    }
}
