//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace OFMProfileAnalyze.Properties
{


    //[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    //[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    [CompilerGenerated, GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed class Settings : ApplicationSettingsBase
    {
        // Fields
        private static Settings defaultInstance = ((Settings)SettingsBase.Synchronized(new Settings()));

        // Properties
        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [UserScopedSetting, DebuggerNonUserCode, DefaultSettingValue("")]
        public string nwscanconfig
        {
            get
            {
                return (string)this["nwscanconfig"];
            }
            set
            {
                this["nwscanconfig"] = value;
            }
        }

        [UserScopedSetting, DebuggerNonUserCode, DefaultSettingValue("")]
        public string nwscanfolderdb
        {
            get
            {
                return (string)this["nwscanfolderdb"];
            }
            set
            {
                this["nwscanfolderdb"] = value;
            }
        }

        [UserScopedSetting, DebuggerNonUserCode, DefaultSettingValue("")]
        public string nwscanrequiredsystem
        {
            get
            {
                return (string)this["nwscanrequiredsystem"];
            }
            set
            {
                this["nwscanrequiredsystem"] = value;
            }
        }

        [UserScopedSetting, DebuggerNonUserCode, DefaultSettingValue("")]
        public string rootenumfolder
        {
            get
            {
                return (string)this["rootenumfolder"];
            }
            set
            {
                this["rootenumfolder"] = value;
            }
        }
    }
}
